esphome:
  name: ajax

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API - I've disabled because not using HA mqtt
# api:
#  encryption:
#    key: "=================================" #usually geneerated automatically

ota:
  password: "================================" #usually geneerated automatically

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
# Optional manual IP
  manual_ip:
    static_ip: # your board ip
    gateway: # your gateway
    subnet: # your subnet
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: # use yours
    password: # use yours

captive_portal:
    
mqtt:
  broker: # mqtt broker IP
  username: # mqtt broker user
  password: # mqtt broker pass
  client_id: AjaxAlarmControl # What you want to call your device in your MQTT broker
  topic_prefix: ajax/alarm/control
  on_message:
    - topic: ajax/alarm
      payload: arm_ajax
      qos: 1
      then:
      - switch.turn_on: arm
    - topic: ajax/alarm
      payload: disarm_ajax
      qos: 1
      then:
      - switch.turn_on: disarm
    - topic: ajax/alarm
      payload: night_ajax
      qos: 1
      then:
      - switch.turn_on: arm_night
        
switch:
  - platform: gpio
    pin: D1 # change with your pin soldered
    inverted: true
    id: "disarm"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: disarm
  - platform: gpio
    pin: D2 # change with your pin soldered
    inverted: true
    id: "arm"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: arm
  - platform: gpio
    pin: D7 # change with your pin soldered
    inverted: true
    id: "arm_night"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: arm_night
